version: "3.8"

services:
  wiremock:
    build:
      context: ../docker/wiremock
      dockerfile: Dockerfile
    container_name: wiremock
    ports:
      - "8081:8080"  # Host port : Container port
    environment:
      - WIREMOCK_ROOT_DIR=/home/wiremock
    volumes:
      - ../docker/wiremock/mappings:/home/wiremock/mappings
      - ../docker/wiremock/__files:/home/wiremock/__files
    command: ["--root-dir", "/home/wiremock"]
    restart: unless-stopped
