
CREATE USER app WITH PASSWORD 'app';
GRANT ALL PRIVILEGES ON DATABASE disaster TO app;

CREATE SCHEMA IF NOT EXISTS drp AUTHORIZATION app;

CREATE TABLE IF NOT EXISTS drp.features (
  id TEXT PRIMARY KEY,
  props JSONB,
  geom geometry(GEOMETRY,4326) NOT NULL
);

GRANT USAGE ON SCHEMA drp TO app;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA drp TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA drp
  GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO app;
